### ISSUE TITLE
Lifter emits cvt_bool_bv(FALSE) rather than simplifying

### ISSUE THREAD

**Issue by ailrst** [UQ-PAC/asl-interpreter#108]
Example: https://katrinafyi.github.io/aslp-web/5/?opcode=0x7100005f&bytes=5F+00+00+71&asm=cmp+w2%2C+%230&debug=0

`not_bits.0 {{ 1 }} ( cvt_bool_bv.0 {{  }} ( FALSE ) )`

I wouldn't expect this to appear since it can would be simplified with straight evaluation.

More broadly it would be desirable to remove casting entirely from the residual programs but I don't know how feasible that is.

Possible heavyhanded fix; might be safer to just simplify at the expression level?

```diff
diff --git a/libASL/dis.ml b/libASL/dis.ml
index 1d7cb52..5612058 100644
--- a/libASL/dis.ml
+++ b/libASL/dis.ml
@@ -1580,6 +1580,8 @@ let dis_core (env: Eval.Env.t) (unroll_bound) ((lenv,globals): env) (decode: dec
     let stmts' = Transforms.CaseSimp.do_transform stmts' in
     let stmts' = Transforms.RemoveRegisters.run stmts' in
     let stmts' = Transforms.AppendZeros.run stmts' in
+    let (_,_,stmts') = (dis_stmts (stmts') config lenv)  in
+    let stmts' = flatten stmts' [] in
 
     if !debug_level >= 2 then begin
         let stmts' = Asl_visitor.visit_stmts (new Asl_utils.resugarClass (!TC.binop_table)) stmts' in

```

**Comment by ncough** [comment]
Managed to clean up this instruction with a few additional rewrites in the partial evaluation phase (#110), but there may still be cases that produce `cvt_bool_bv.0 {{  }} ( FALSE )` due to late analysis and reductions. `0x7100005f` should be:

```
PSTATE . V = '0' ;
PSTATE . C = '1' ;
PSTATE . Z = cvt_bool_bv.0 {{  }} ( eq_bits.0 {{ 32 }} ( 
  __array _R [ 2 ] [ 0 +: 32 ],'00000000000000000000000000000000' ) ) ;
PSTATE . N = __array _R [ 2 ] [ 31 +: 1 ] ;
```

We could eliminate casting, but I suspect it would require a set of primitive comparison operations that return a single bit, rather than a boolean. We have other contexts that would still require the boolean variants, such as if statements.
